language: node_js
node_js: '12'
dist: bionic
install:
- npm ci
services:
- xvfb
matrix:
  include:
  - name: 'Firefox'
    addons:
      firefox: latest-unsigned
    script:
    - npm test
    - npm run libraries
    - npm run webpack:build:firefox
    - npm run test:build
  - name: 'Chromium'
    addons:
      chrome: stable
    script:
    - npm test
    - npm run libraries
    - npm run webpack:build:chromium
    - npm run test:build
  - name: 'Scripts'
    script:
      - cd scripts
      - npm i
      - npm start -- -
