name: Firefox Build Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    name: node${{ matrix.node-versions }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up node ${{ matrix.node-versions }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-versions }}

      - name: Install dependencies & test & build
        run: |
          npm ci
          npm test
          npm run libraries
          npm run webpack:build:firefox
          npm run test:build